version: '3.8'

services:
  flask-app1:
    build: ./flask
    container_name: flask_app_1
    ports:
      - "3000:3333"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    links:
      - mongodb
    networks: #if not set, use default
      - app-network
      - webnet 

  flask-app2:
    build: ./flask
    container_name: flask_app_2
    ports:
      - "4000:3333"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    links:
      - mongodb
    networks: #if not set, use default
      - app-network
      - webnet 
  
  flask-app3:
    build: ./flask
    container_name: flask_app_3
    ports:
      - "5000:3333"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    links:
      - mongodb
    networks: #if not set, use default
      - app-network
      - webnet 
  
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8000:80"
    depends_on: #tell nginx should start after flask
      - flask-app1
      - flask-app2
      - flask-app3
    networks:
      - webnet

  mongodb:
    hostname: mongodb
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks: #if not set, use default
      - app-network

networks: # if not set, use default
  app-network:
    driver: bridge
  webnet:
    driver: bridge
