version: '3.8'

services:
  flask-app:
    build:
      context: ./flask
    ports:
      - "3000:3333"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    links:
      - mongodb
    networks: #if not set, use default
      - app-network 

  mongodb:
    hostname: mongodb
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks: #if not set, use default
      - app-network

networks: # if not set, use default
  app-network:
    driver: bridge
